
default: &default
  host: localhost
  adapter: postgresql
  username: javier
  password: javier
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: sky

test:
  <<: *default
  database: sky-test

